config/routes.rb
TipTrick::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :tips, only: [:new, :create, :show, :index, :destroy, :edit, :update, :proceed]
  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/tip.rb
class Tip < ActiveRecord::Base
	belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true

end

app/models/tips.rb
class Tips < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tips
	#callback
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
					  				length: { minimum: 10}, 
					  				format: { with: VALID_EMAIL_REGEX },
									  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	
	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "Welcome to Tips/tricks"
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

	def destroy
		sign_out
    flash[:success] = "You have signed out! Come back soon!"
    redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def help
  end

  def about
  end

  def contact
  end

  def search 
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
	before_action :signed_in_user, only: [:new, :create, :index, :show, :destroy, :edit, :update]
	before_action :correct_user,   only: [:destroy, :edit]
  before_action :new
	
  def new
		@tips = Tip.new
	end

	def create
		@tips = current_user.tips.build(tips_params)
		if @tips.save
			flash[:success] = "Tip created!"
      redirect_to tips_path
    else
    	@feed_item = []
      render 'static_pages/home'
    end
  end

	def index
		@tips = Tip.all
	end

	def show
  	@tips = Tip.find(params[:id])
	end

	def destroy
    @tip.destroy
    redirect_to current_user
  end

  def edit
  	@tip = Tip.find(params[:id])
  end

  def update
  	@tip = Tip.find(params[:id])
    if @tip.update_attributes(tips_params)
      flash[:success] = "Tip updated!"
      redirect_to tips_path
    else
    	flash[:alert] = "You can't edit that fool!"
    	render tips_path
    end
  end

private

    def tips_params
      params.require(:tip).permit(:content)
    end

    def correct_user
      @tip = current_user.tips.find_by(id: params[:id])
      redirect_to root_url if @tip.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @tips = @user.tips.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to Tips/tricks"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def destroy
  end

 private
   
   def user_params
  			params.require(:user).permit(:name, :email, :password, :password_confirmation)
 	 end
 	 
 	 def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

   def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Tip/trick"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

 def signed_in?
 	!current_user.nil?
 end

 def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
 def current_user=(user)
 	@current_user = user
 end

 def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

 def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
def gravatar_for(user, options = { size: 75 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    tip/trick
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help",  help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Tips/tricks", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Tips", tips_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Post", help_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TipTrick | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_posthelp.html.erb
<h1>This is what you need to do to add a new post</h1>

<%= link_to "Proceed to post", new_tip_path, class: "btn btn-large btn-primary" %>

app/views/shared/_tip.html.erb
<li id="<%= tip.id %>">
  <%= link_to gravatar_for(tip.user), tip.user %>
  <span class="user">
    <%= link_to tip.user.name, tip.user %>
  </span>
  <span class="content"><%= tip.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tip.created_at) %> ago.
  </span>
  <% if current_user?(tip.user) %>
    <%= link_to "delete", tip, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: tip.content %>
  <% end %>
</li>

app/views/shared/_tips.html.erb
<div class="tip">
<li id="<%= tips.id %>">
 
  <span class="user"><strong><%= tip.user.name %></strong>
  </span>

  <span class="content"><%= link_to tip.content, tip_path(tip) %>
  </span>
  <span class="timestamp">Posted <%= time_ago_in_words(tip.created_at) %> ago.
  </span>

  <span class="hidde">
    <% if current_user?(tip.user) %>
    <%= link_to "Delete", tip, method: :delete,
                                     data: { confirm: "If you delete this, it's not coming back. Maybe, you would rather edit this tip." },
                                    title: tip.content %> |
    <span class="edit"><%= link_to "Edit", edit_tip_path(tip) %></span>
  <% end %> |
  <span class="view"><%= link_to "View #{user.name} profile", user.name %></span>
</span>
</li>
</div>

app/views/shared/_tips_form.html.erb
<%= form_for(:tip, url: tips_path) do |f| %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new tips..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.tips.count, "tip") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About</h1>
	<p>We have tips, you have tips, we have a place to post them, so we can ALL have tips.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
	<p>Where we be.</p>

app/views/static_pages/help.html.erb
<h1>This is what you need to do to add a new post</h1>
<p>
You must post a tip, anything but a tip will automatically result in expulsion. FOR EVER!

</p>

<%= link_to "Proceed to post", new_tip_path, class: "btn btn-small btn-primary" %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
  <h1>Welcome to the tips/tricks</h1>

  <h2>
    This is the home page tips/tricks site.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/tips/_tip.html.erb
<div class="tips">
<li id="<%= tip.id %>">
  <span class="user"><strong><%= link_to tip.user.name, user_path(tip.user.id) %></strong>
  </span>
  <%= link_to gravatar_for(current_user, size: 52), current_user %>

  <span class="content"><%= link_to tip.content, tip_path(tip) %>
  </span>
  <span class="timestamp">Posted <%= time_ago_in_words(tip.created_at) %> ago.
  </span>

  <span class="hidden">
    <% if current_user?(tip.user) %>
    <%= link_to "Delete", tip, method: :delete,
                                     data: { confirm: "If you delete this, it's not coming back. Maybe, you would rather edit this tip." },
                                    title: tip.content %> |
    <span class="edit"><%= link_to "Edit", edit_tip_path(tip) %></span>
  <% end %> 
</span>
</li>
</div>

app/views/tips/_tip_content.html.erb
<% provide(:title, "The Tip") %>
<h1>Tip</h1>
<li><%= @tips.content %></li>
<%= link_to "Back to Tips", tips_path %>
  
  

app/views/tips/_tips.html.erb
<li>
  <span class="content"><%= tip.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tip.created_at) %> ago.
  </span>
  <% if current_user?(tip.user) %>
    <%= link_to "delete", tip, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: tip.content %>
  <% end %>
</li>

app/views/tips/edit.html.erb
<% provide(:title, "Edit Tip") %>
<h1>Update your Tip</h1>
<%= form_for @tip do |f| %>
  
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new tips..." %>
  </div>
  <%= f.submit "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/tips/index.html.erb
<% provide(:title, "Tip") %>
<h1>Tips</h1>
<%= render @tips %>  

app/views/tips/show.html.erb
<% provide(:title, "Tip Content") %>
<%= render "tip_content" %>  

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All tips') %>
<h1>All tips</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
   <div class="span8">
    <% if @user.tips.any? %>
      <h3>Tips (<%= @user.tips.count %>)</h3>
      <ol class="tips">
        <%= render @tips %>
      </ol>
    <% end %>
  </div>
</div>